"""02_files_schemas

Revision ID: 983ac0cd9518
Revises: ae2aa16912d0
Create Date: 2022-10-30 17:16:44.081368

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '983ac0cd9518'
down_revision = 'ae2aa16912d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
